repos:
  - repo: local
    hooks:
      - id: test-suite-with-coverage
        name: Test suite with coverage of at least 90%
        entry: uv run pytest --cov --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
