from datetime import datetime
from typing import Protocol
from uuid import UUID

from modules.organizations.application.repositories.auth_repository import SecurityAuditEvent
from modules.organizations.domain.model import (
    CNPJ,
    Church,
    ChurchMembership,
    ChurchSettings,
    ChurchSlug,
    Congregation,
    EmailAddress,
    User,
)


class IRegistrationRepository(Protocol):
    async def user_exists_by_email(self, email: EmailAddress) -> bool: ...
    async def church_exists_by_slug(self, slug: ChurchSlug) -> bool: ...
    async def church_exists_by_document(self, document: CNPJ) -> bool: ...
    async def add_church(self, church: Church) -> None: ...
    async def add_user(self, user: User) -> None: ...
    async def add_congregation(self, congregation: Congregation) -> None: ...
    async def add_membership(self, membership: ChurchMembership) -> None: ...
    async def add_settings(self, settings: ChurchSettings) -> None: ...
    async def add_email_verification(
        self, user_id: UUID, token_hash: str, expires_at: datetime
    ) -> None: ...
    async def add_audit_event(self, event: SecurityAuditEvent) -> None: ...
