from datetime import datetime
from typing import Protocol
from uuid import UUID


class IPasswordVerifier(Protocol):
    def verify(self, plain_text: str, password_hash: str) -> bool: ...


class ITokenService(Protocol):
    def generate_opaque(self) -> str: ...
    def hash_opaque(self, token: str) -> str: ...
    def issue_access(self, user_id: UUID, session_id: UUID, now: datetime) -> tuple[str, int]: ...
    def decode_access(self, token: str, now: datetime) -> tuple[UUID, UUID]: ...


class IEmailSender(Protocol):
    async def send_email_verification(self, email: str, token: str) -> None: ...
    async def send_password_reset(self, email: str, token: str) -> None: ...


class IRateLimiter(Protocol):
    async def ensure_allowed(self, key: str, limit: int, window_seconds: int) -> None: ...
